name: "Install meshery"
on: [pull_request, push]

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: engineerd/setup-kind@v0.5.0
      - uses: DelusionalOptimist/setup-meshery-demo@main
        with:
          milliseconds: 1000
      - name: Testing
        run: |
          kubectl cluster-info
